name: ci_formatting

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: updating available system dependencies
      run: sudo apt-get update
    - name: installing system dependencies
      run: sudo apt-get install -y build-essential pkg-config automake libncurses5-dev autotools-dev libparted-dev libconfig-dev libconfig++-dev dmidecode clang-format
    - name: creating autoconf files
      run: ./autogen.sh
    - name: configuring
      run: ./configure CFLAGS='-O0 -g -Wall -Wextra'
    - name: verifying code style
      run: make check-format
